services:
  api:
    build: .
    image: image-health-monitor
    container_name: api-health-monitor
    volumes:
      - ./application:/application
    ports:
      - 9501:9501
    networks:
      - app-network

  database:
    image: mysql:8
    container_name: db-health-monitor
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=dev_database
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_USER=root
    ports:
      - 4307:3306
    networks:
      - app-network

networks:
  app-network:
    driver: bridge